version: "3"
services:
  wordpress:
    image: wordpress:6.2.2-php8.0-fpm
    volumes:
      - ./wordpress/:/var/www/html
    container_name: p2_wordpress
    depends_on:
      - p2_db
  nginx:
    image: nginx:latest
    container_name: p2_server
    volumes:
      - ./wordpress/:/var/www/html
      - ./nginx/nginx.conf/:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx
      - ./etc/letsencrypt:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    depends_on:
      - wordpress
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: p2_certbot
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./wordpress/:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email aleksander.freelancer@gmail.com --agree-tos --no-eff-email -d legal-services.site
  p2_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: p2_db
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: p2_db
    container_name: p2_admin
