version: "3"
services:
  wordpress:
    image: wordpress:6.2.2-php8.0-fpm
    volumes:
      - ./wordpress/:/var/www/html
    ports:
      - 8000:9000
    container_name: p2_wordpress
    depends_on:
      - db
  nginx:
    image: nginx:latest
    container_name: p2_server
    volumes:
      - ./wordpress/:/var/www/html
      - ./nginx/nginx.conf/:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx
      - ./etc/letsencrypt:/etc/letsencrypt
    ports:
      - 150:120
      - 443:443
    depends_on:
      - wordpress
  # certbot:
  #   image: certbot/certbot
  #   depends_on:
  #     - nginx
  #   container_name: certbot
  #   volumes:
  #     - ./etc/letsencrypt:/etc/letsencrypt
  #     - ./wordpress/:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email pavlenko.at@mail.ru --agree-tos --no-eff-email -d cosmos-prosto.space
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    container_name: p2_db
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - default
    command: --default-authentication-plugin=mysql_native_password
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    networks:
      - default
    environment:
      PMA_HOST: db
    container_name: p2_admin

networks:
  default:
    driver: bridge
